name: humble-devel

on:
  pull_request:
    branches:
      - humble-devel
  push:
    branches:
      - humble-devel

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Install popf deps
        run: sudo apt-get install libfl-dev
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.3.3
        with:
          required-ros-distributions: humble
      - name: Create custom repos
        run: wget -O /tmp/all.repos https://raw.githubusercontent.com/fmrico/book_ros2/humble-devel/third_parties.repos
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.5
        with:
          package-name: br2_behavior_trees br2_hfsm_behaviors br2_intro_ros2 br2_kobuki br2_navigation br2_reactive_behaviors
          target-ros2-distro: humble
          vcs-repo-file-url: /tmp/all.repos
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
