name: jazzy-devel

on:
  pull_request:
    branches:
      - jazzy-devel
  push:
    branches:
      - jazzy-devel

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:jazzy-desktop
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y wget python3-vcstool python3-colcon-coveragepy-result
      - name: Create custom repos
        run: wget -O /tmp/all.repos https://raw.githubusercontent.com/fmrico/book_ros2/jazzy-devel/third_parties.repos
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.15
        with:
          package-name: br2_basics br2_bt_bumpgo br2_bt_patrolling br2_fsm_bumpgo_cpp br2_fsm_bumpgo_py br2_navigation br2_tf2_detector br2_tiago br2_tracking br2_tracking_msgs br2_vff_avoidance
          target-ros2-distro: jazzy
          vcs-repo-file-url: /tmp/all.repos
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
