name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Install popf deps
        run: sudo apt-get install libfl-dev
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.2.1
        with:
          required-ros-distributions: foxy
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.3
        with:
          package-name: mr2_behavior_trees mr2_hfsm_behaviors mr2_intro_ros2 mr2_kobuki mr2_navigation mr2_reactive_behaviors
          target-ros2-distro: foxy
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/main/index.yaml
