name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.4.0
      - name: Create custom repos
        run: wget -O /tmp/all.repos https://raw.githubusercontent.com/fmrico/book_ros2/main/.github/third_parties_ci.repos
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: br2_basics br2_bt_bumpgo br2_bt_patrolling br2_fsm_bumpgo_cpp br2_fsm_bumpgo_py br2_navigation br2_tf2_detector br2_tiago br2_tracking br2_tracking_msgs br2_vff_avoidance
          target-ros2-distro: humble
          vcs-repo-file-url: /tmp/all.repos
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
